# Generated by Django 5.1.9 on 2026-05-11 11:53

import adl_siapmicros_polarisweb_plugin.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0037_alter_dispatchchannel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolarisWebConnection',
            fields=[
                ('networkconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.networkconnection')),
                ('host', models.URLField(help_text='IP Address or domain name to connect to. Should include http:// or https:// and no trailing slash and the port where applicable.', verbose_name='Host IP Address or domain name')),
                ('api_token', models.CharField(max_length=512, verbose_name='API Token')),
            ],
            options={
                'verbose_name': 'Polaris Web API Connection',
                'verbose_name_plural': 'Polaris Web API Connections',
            },
            bases=('core.networkconnection',),
        ),
        migrations.CreateModel(
            name='PolarisWebStationLink',
            fields=[
                ('stationlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stationlink')),
                ('polaris_station_id', models.IntegerField(verbose_name='Polaris Station')),
                ('start_date', models.DateTimeField(blank=True, help_text='The date to start collecting data on the first run. Ignored if data has already been collected for this station.', null=True, validators=[adl_siapmicros_polarisweb_plugin.validators.validate_start_date], verbose_name='Initial Collection Start Date')),
            ],
            options={
                'verbose_name': 'Polaris Web Station Link',
                'verbose_name_plural': 'Polaris Web Station Links',
            },
            bases=('core.stationlink',),
        ),
        migrations.CreateModel(
            name='PolarisWebVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('polaris_measure_id', models.IntegerField(verbose_name='Polaris Measure')),
                ('adl_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='ADL Parameter')),
                ('network_connection', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_siapmicros_polarisweb_plugin.polariswebconnection')),
                ('polaris_measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='Polaris Measure Unit')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
