# Generated by Django 6.0.5 on 2026-05-21 07:11
#
# The example address in this help text was edited in place, rather than
# changed by a later migration, so that a live national deployment's IP is not
# left recorded anywhere in the repository. help_text emits no DDL — it exists
# in migration state only for the autodetector — so an applied 0002 is
# unaffected on any existing database and a fresh migrate produces the same
# schema.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_siapmicros_polarisweb_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polariswebconnection',
            name='host',
            field=models.URLField(help_text='e.g. http://192.0.2.10:88', verbose_name='Host'),
        ),
    ]
