# Generated by Django 6.0.5 on 2026-05-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_siapmicros_polarisweb_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polariswebconnection',
            name='host',
            field=models.URLField(help_text='e.g. http://102.218.136.213:88', verbose_name='Host'),
        ),
    ]
